// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Account = "_Account";
                public readonly string _Main = "_Main";
                public readonly string Create = "Create";
                public readonly string Edit = "Edit";
                public readonly string Index = "Index";
                public readonly string NotRealizedYet = "NotRealizedYet";
            }
            public readonly string _Account = "~/Areas/Admin/Views/Shared/_Account.cshtml";
            public readonly string _Main = "~/Areas/Admin/Views/Shared/_Main.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Shared/Create.cshtml";
            public readonly string Edit = "~/Areas/Admin/Views/Shared/Edit.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Shared/Index.cshtml";
            public readonly string NotRealizedYet = "~/Areas/Admin/Views/Shared/NotRealizedYet.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string ozi_Checkbox = "ozi_Checkbox";
                public readonly string ozi_Currency = "ozi_Currency";
                public readonly string ozi_Date = "ozi_Date";
                public readonly string ozi_Filter = "ozi_Filter";
                public readonly string ozi_Header = "ozi_Header";
                public readonly string ozi_String = "ozi_String";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string FakeView = "FakeView";
                public readonly string ozi_Checkbox = "ozi_Checkbox";
                public readonly string ozi_Code = "ozi_Code";
                public readonly string ozi_Collection = "ozi_Collection";
                public readonly string ozi_Currency = "ozi_Currency";
                public readonly string ozi_Date = "ozi_Date";
                public readonly string ozi_File = "ozi_File";
                public readonly string ozi_Hidden = "ozi_Hidden";
                public readonly string ozi_Object = "ozi_Object";
                public readonly string ozi_Select = "ozi_Select";
                public readonly string ozi_Static = "ozi_Static";
                public readonly string ozi_String = "ozi_String";
                public readonly string ozi_Textarea = "ozi_Textarea";
                public readonly string ozi_Wysiwyg = "ozi_Wysiwyg";
                public readonly string ReferralExplains = "ReferralExplains";
                public readonly string ReferralFields = "ReferralFields";
                public readonly string StartDistribution = "StartDistribution";
                public readonly string Subscription = "Subscription";
                public readonly string SubscriptionGroup = "SubscriptionGroup";
                static readonly _CollectionsClass s_Collections = new _CollectionsClass();
                public _CollectionsClass Collections { get { return s_Collections; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _CollectionsClass
                {
                    public readonly string ozi_File = "ozi_File";
                    public readonly string ozi_Select = "ozi_Select";
                    public readonly string ozi_String = "ozi_String";
                    public readonly string ozi_Textarea = "ozi_Textarea";
                }
                static readonly _SharedClass s_Shared = new _SharedClass();
                public _SharedClass Shared { get { return s_Shared; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _SharedClass
                {
                    public readonly string ObjectFields = "ObjectFields";
                }
            }
            static readonly _FormClass s_Form = new _FormClass();
            public _FormClass Form { get { return s_Form; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _FormClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string FormButtons = "FormButtons";
                }
                public readonly string FormButtons = "~/Areas/Admin/Views/Shared/Form/FormButtons.cshtml";
            }
            static readonly _GlobalActionsClass s_GlobalActions = new _GlobalActionsClass();
            public _GlobalActionsClass GlobalActions { get { return s_GlobalActions; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _GlobalActionsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Create = "Create";
                }
                public readonly string Create = "~/Areas/Admin/Views/Shared/GlobalActions/Create.cshtml";
            }
            static readonly _ListActionsClass s_ListActions = new _ListActionsClass();
            public _ListActionsClass ListActions { get { return s_ListActions; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _ListActionsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Delete = "Delete";
                    public readonly string Edit = "Edit";
                    public readonly string Sort = "Sort";
                    public readonly string Visibility = "Visibility";
                }
                public readonly string Delete = "~/Areas/Admin/Views/Shared/ListActions/Delete.cshtml";
                public readonly string Edit = "~/Areas/Admin/Views/Shared/ListActions/Edit.cshtml";
                public readonly string Sort = "~/Areas/Admin/Views/Shared/ListActions/Sort.cshtml";
                public readonly string Visibility = "~/Areas/Admin/Views/Shared/ListActions/Visibility.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
