// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Breadcrumbs = "_Breadcrumbs";
                public readonly string _Layout = "_Layout";
                public readonly string _SidebarMaster = "_SidebarMaster";
                public readonly string NotFound = "NotFound";
            }
            public readonly string _Breadcrumbs = "~/Views/Shared/_Breadcrumbs.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _SidebarMaster = "~/Views/Shared/_SidebarMaster.cshtml";
            public readonly string NotFound = "~/Views/Shared/NotFound.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string File = "File";
                public readonly string PagerViewModel = "PagerViewModel";
                public readonly string ReferralViewModel = "ReferralViewModel";
                static readonly _FieldsClass s_Fields = new _FieldsClass();
                public _FieldsClass Fields { get { return s_Fields; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _FieldsClass
                {
                    public readonly string checkbox = "checkbox";
                    public readonly string multicheckbox = "multicheckbox";
                    public readonly string @string = "string";
                    public readonly string stringcheckbox = "stringcheckbox";
                    public readonly string textarea = "textarea";
                }
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string LogInViewModel = "LogInViewModel";
                public readonly string RecPasswordViewModel = "RecPasswordViewModel";
                public readonly string ReferralViewModel = "ReferralViewModel";
                public readonly string RegisterViewModel = "RegisterViewModel";
                public readonly string SettingsViewModel = "SettingsViewModel";
                static readonly _FieldsClass s_Fields = new _FieldsClass();
                public _FieldsClass Fields { get { return s_Fields; } }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public partial class _FieldsClass
                {
                    public readonly string checkbox = "checkbox";
                    public readonly string multicheckbox = "multicheckbox";
                    public readonly string @string = "string";
                    public readonly string stringcheckbox = "stringcheckbox";
                    public readonly string textarea = "textarea";
                }
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
